package mockdata

import (
	"opsramp-agent/opsramp"
)

// GetAlerts returns realistic mock alert data matching OpsRamp API schema.
func GetAlerts() []opsramp.Alert {
	return []opsramp.Alert{
		{
			UniqueID:     "ALR-20260219-001",
			Subject:      "CPU utilization exceeded 95% on web-server-prod-01",
			CurrentState: "Critical",
			ServiceName:  "CPU",
			ProblemArea:  "CPU",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     true,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "CPU",
			AlertTime:    "2026-02-19T08:15:00+0000",
			Device: opsramp.Device{
				ID: "res-001", Name: "web-server-prod-01",
				HostName: "web-server-prod-01", IPAddress: "10.0.1.101",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-001", Name: "web-server-prod-01",
				HostName: "web-server-prod-01", IPAddress: "10.0.1.101",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "AWS", Region: "us-east-1", InstanceSize: "c5.2xlarge",
			},
			Metric:      "system.cpu.utilization",
			MonitorName: "CPU Utilization Monitor",
			RepeatCount: "5",
			Status:      "New",
			Priority:    "P1",
			ElapsedTime: "3h 45m",
			CreatedDate: "2026-02-19T08:15:00+0000",
			UpdatedTime: "2026-02-19T11:50:00+0000",
			Description: "CPU utilization has been above 95% for the last 15 minutes. Current value: 97.3%. Threshold: 90%.",
			EntityType:  "RESOURCE",
			EventType:   "ALERT",
			IncidentID:  "INC-20260219-001",
		},
		{
			UniqueID:     "ALR-20260219-002",
			Subject:      "Disk usage at 92% on db-primary-01",
			CurrentState: "Critical",
			ServiceName:  "DISK",
			ProblemArea:  "DISK",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "DISK",
			AlertTime:    "2026-02-19T06:30:00+0000",
			Device: opsramp.Device{
				ID: "res-005", Name: "db-primary-01",
				HostName: "db-primary-01", IPAddress: "10.0.2.10",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-005", Name: "db-primary-01",
				HostName: "db-primary-01", IPAddress: "10.0.2.10",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "AWS", Region: "us-east-1", InstanceSize: "r6g.4xlarge",
			},
			Metric:      "system.disk.utilization",
			MonitorName: "Disk Space Monitor",
			RepeatCount: "12",
			Status:      "New",
			Priority:    "P0",
			ElapsedTime: "5h 30m",
			CreatedDate: "2026-02-19T06:30:00+0000",
			UpdatedTime: "2026-02-19T11:45:00+0000",
			Description: "Root disk /dev/sda1 is at 92% capacity. Growth rate: ~2% per day. Projected to reach 100% in 4 days.",
			EntityType:  "RESOURCE",
			EventType:   "ALERT",
		},
		{
			UniqueID:     "ALR-20260219-003",
			Subject:      "Memory utilization at 88% on app-server-prod-02",
			CurrentState: "Warning",
			ServiceName:  "MEMORY",
			ProblemArea:  "MEMORY",
			Acknowledged: true,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "MEMORY",
			AlertTime:    "2026-02-19T09:00:00+0000",
			Device: opsramp.Device{
				ID: "res-003", Name: "app-server-prod-02",
				HostName: "app-server-prod-02", IPAddress: "10.0.1.103",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-003", Name: "app-server-prod-02",
				HostName: "app-server-prod-02", IPAddress: "10.0.1.103",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "AWS", Region: "us-east-1", InstanceSize: "m5.xlarge",
			},
			Metric:      "system.memory.utilization",
			MonitorName: "Memory Monitor",
			RepeatCount: "3",
			Status:      "Acknowledged",
			Priority:    "P3",
			ElapsedTime: "2h 50m",
			CreatedDate: "2026-02-19T09:00:00+0000",
			UpdatedTime: "2026-02-19T09:15:00+0000",
			Description: "Memory utilization is at 88%. Java heap consuming 6.2GB of 8GB allocated.",
		},
		{
			UniqueID:     "ALR-20260219-004",
			Subject:      "SSL certificate expires in 7 days for api.acme.com",
			CurrentState: "Warning",
			ServiceName:  "SSL",
			ProblemArea:  "SSL Certificate",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "SSL",
			AlertTime:    "2026-02-19T00:00:00+0000",
			Device: opsramp.Device{
				ID: "res-010", Name: "api-gateway-prod",
				HostName: "api-gateway-prod", IPAddress: "10.0.3.50",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-010", Name: "api-gateway-prod",
				HostName: "api-gateway-prod", IPAddress: "10.0.3.50",
				Type: "Linux", State: "active", OSName: "Amazon Linux 2023",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "AWS", Region: "us-east-1", InstanceSize: "t3.medium",
			},
			Metric:      "ssl.certificate.expiry.days",
			MonitorName: "SSL Certificate Monitor",
			RepeatCount: "1",
			Status:      "New",
			Priority:    "P1",
			ElapsedTime: "12h",
			CreatedDate: "2026-02-19T00:00:00+0000",
			UpdatedTime: "2026-02-19T00:00:00+0000",
			Description: "SSL certificate for api.acme.com expires on 2026-02-26. Renew immediately to avoid service disruption.",
		},
		{
			UniqueID:     "ALR-20260219-005",
			Subject:      "Network latency spike on k8s-node-03 (avg 250ms)",
			CurrentState: "Warning",
			ServiceName:  "NETWORK",
			ProblemArea:  "NETWORK",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "NETWORK",
			AlertTime:    "2026-02-19T10:30:00+0000",
			Device: opsramp.Device{
				ID: "res-015", Name: "k8s-node-03",
				HostName: "k8s-node-03", IPAddress: "10.0.4.23",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-015", Name: "k8s-node-03",
				HostName: "k8s-node-03", IPAddress: "10.0.4.23",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "HPE GreenLake", Region: "hpe-dc-east",
			},
			Metric:      "network.latency.avg",
			MonitorName: "Network Latency Monitor",
			RepeatCount: "2",
			Status:      "New",
			Priority:    "P3",
			ElapsedTime: "1h 20m",
			CreatedDate: "2026-02-19T10:30:00+0000",
			UpdatedTime: "2026-02-19T10:45:00+0000",
			Description: "Average network latency is 250ms, exceeding the 100ms threshold. Possible network congestion or DNS resolution delays.",
		},
		{
			UniqueID:     "ALR-20260218-006",
			Subject:      "Azure SQL Database DTU consumption at 85%",
			CurrentState: "Warning",
			ServiceName:  "DATABASE",
			ProblemArea:  "DATABASE",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "DATABASE",
			AlertTime:    "2026-02-18T22:00:00+0000",
			Device: opsramp.Device{
				ID: "res-020", Name: "azure-sql-prod-01",
				HostName: "azure-sql-prod-01.database.windows.net", IPAddress: "",
				Type: "CLOUD", ResourceType: "Azure SQL Database",
			},
			Resource: opsramp.Resource{
				ID: "res-020", Name: "azure-sql-prod-01",
				HostName: "azure-sql-prod-01.database.windows.net",
				Type:     "Azure SQL Database", State: "active",
				AgentInstalled: false, Status: "managed", ResourceType: "Azure SQL Database",
				Cloud: "Azure", Region: "eastus",
			},
			Metric:      "azure.sql.dtu.percent",
			MonitorName: "Azure SQL Monitor",
			RepeatCount: "8",
			Status:      "New",
			Priority:    "P3",
			ElapsedTime: "14h",
			CreatedDate: "2026-02-18T22:00:00+0000",
			UpdatedTime: "2026-02-19T10:00:00+0000",
			Description: "DTU consumption at 85% on Standard S3 tier. Consider scaling up or optimizing queries.",
		},
		{
			UniqueID:     "ALR-20260219-007",
			Subject:      "PING failed for monitoring-agent-staging-01",
			CurrentState: "Critical",
			ServiceName:  "PING",
			ProblemArea:  "Availability",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     true,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "PING",
			AlertTime:    "2026-02-19T11:00:00+0000",
			Device: opsramp.Device{
				ID: "res-025", Name: "monitoring-agent-staging-01",
				HostName: "monitoring-agent-staging-01", IPAddress: "172.16.0.50",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-025", Name: "monitoring-agent-staging-01",
				HostName: "monitoring-agent-staging-01", IPAddress: "172.16.0.50",
				Type: "Linux", State: "active", OSName: "CentOS 8",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "OnPrem", Region: "datacenter-east",
			},
			Metric:      "ping.status",
			MonitorName: "PING Monitor",
			RepeatCount: "20",
			Status:      "New",
			Priority:    "P0",
			ElapsedTime: "50m",
			CreatedDate: "2026-02-19T11:00:00+0000",
			UpdatedTime: "2026-02-19T11:50:00+0000",
			Description: "Host is unreachable. 20 consecutive ping failures. Last successful ping at 10:58 AM.",
			EntityType:  "RESOURCE",
			EventType:   "ALERT",
			IncidentID:  "INC-20260219-004",
		},
		{
			UniqueID:     "ALR-20260219-008",
			Subject:      "Container restart loop detected on greenlake-portal pod",
			CurrentState: "Critical",
			ServiceName:  "CONTAINER",
			ProblemArea:  "Container Health",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "CONTAINER",
			AlertTime:    "2026-02-19T09:45:00+0000",
			Device: opsramp.Device{
				ID: "res-016", Name: "k8s-node-04",
				HostName: "k8s-node-04", IPAddress: "10.0.4.24",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-016", Name: "k8s-node-04",
				HostName: "k8s-node-04", IPAddress: "10.0.4.24",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "HPE GreenLake", Region: "hpe-dc-east",
			},
			Metric:      "container.restart.count",
			MonitorName: "Kubernetes Container Monitor",
			RepeatCount: "7",
			Status:      "New",
			Priority:    "P0",
			ElapsedTime: "2h 5m",
			CreatedDate: "2026-02-19T09:45:00+0000",
			UpdatedTime: "2026-02-19T11:50:00+0000",
			Description: "Pod greenlake-portal-7d8f9a has restarted 7 times in the last 2 hours. CrashLoopBackOff detected. Last exit code: 137 (OOMKilled).",
			EntityType:  "RESOURCE",
			EventType:   "ALERT",
		},
		{
			UniqueID:     "ALR-20260219-009",
			Subject:      "HTTP response time exceeded 5s for greenlake-portal (avg 6.2s)",
			CurrentState: "Critical",
			ServiceName:  "HTTP",
			ProblemArea:  "Application Performance",
			Acknowledged: false,
			Suppressed:   false,
			Closed:       false,
			Ticketed:     false,
			AlertType:    "Monitoring",
			App:          "OpsRamp",
			Component:    "HTTP",
			AlertTime:    "2026-02-19T10:15:00+0000",
			Device: opsramp.Device{
				ID: "res-016", Name: "k8s-node-04",
				HostName: "k8s-node-04", IPAddress: "10.0.4.24",
				Type: "DEVICE", ResourceType: "Linux",
			},
			Resource: opsramp.Resource{
				ID: "res-016", Name: "k8s-node-04",
				HostName: "k8s-node-04", IPAddress: "10.0.4.24",
				Type: "Linux", State: "active", OSName: "Ubuntu 22.04",
				AgentInstalled: true, Status: "managed", ResourceType: "Linux",
				Cloud: "HPE GreenLake", Region: "hpe-dc-east",
			},
			Metric:      "http.response.time",
			MonitorName: "Application HTTP Monitor",
			RepeatCount: "15",
			Status:      "New",
			Priority:    "P1",
			ElapsedTime: "1h 35m",
			CreatedDate: "2026-02-19T10:15:00+0000",
			UpdatedTime: "2026-02-19T11:50:00+0000",
			Description: "GreenLake portal HTTP response time averaging 6.2 seconds, exceeding 5s threshold. 30% of requests timing out. Tenants reporting slow console experience. Service endpoint: greenlake-portal.prod.svc.cluster.local:8443",
			EntityType:  "RESOURCE",
			EventType:   "ALERT",
		},
	}
}
