package mockdata

import (
	"opsramp-agent/opsramp"
)

// GetIncidents returns realistic incident data matching OpsRamp API schema.
func GetIncidents() []opsramp.Incident {
	return []opsramp.Incident{
		{
			ID:          "INC-20260219-001",
			Subject:     "Production web tier degraded - high CPU on web-server-prod-01",
			Description: "web-server-prod-01 is experiencing sustained CPU utilization above 95%. Response times for the web tier have increased from an average of 120ms to 1.8s. Correlated alert: ALR-20260219-001. Initial investigation suggests a runaway Java process (PID 34521) consuming excessive CPU.",
			Status:      "Open",
			SubStatus:   "In Progress",
			Priority:    "High",
			AssignedTo: opsramp.User{
				ID: "usr-001", LoginName: "achen",
				FirstName: "Alex", LastName: "Chen",
				Name: "Alex Chen", Email: "alex.chen@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "system", LoginName: "system",
				FirstName: "OpsRamp", LastName: "System",
				Name: "OpsRamp System", Email: "system@opsramp.com",
			},
			CreatedDate: "2026-02-19T08:20:00+0000",
			UpdatedTime: "2026-02-19T10:30:00+0000",
			Source:      "ALERT",
			Category:    &opsramp.Category{ID: "1", UniqueID: "CAT-INF", Name: "Infrastructure"},
			SubCategory: &opsramp.Category{ID: "10", UniqueID: "SCAT-COMP", Name: "Compute"},
			SLADetails:  &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 600, ResolutionTime: 7200},
			AlertIDs:    []string{"ALR-20260219-001"},
			ResourceIDs: []string{"res-001"},
		},
		{
			ID:          "INC-20260219-002",
			Subject:     "Database disk space critical - db-primary-01 at 92%",
			Description: "Primary PostgreSQL database server disk is at 92% capacity and growing at ~2% per day. WAL archiving and pg_dump backup files are consuming additional space. Immediate action required to prevent database crash. Correlated alert: ALR-20260219-002.",
			Status:      "Open",
			SubStatus:   "Waiting for Approval",
			Priority:    "Urgent",
			AssignedTo: opsramp.User{
				ID: "usr-002", LoginName: "msantos",
				FirstName: "Maria", LastName: "Santos",
				Name: "Maria Santos", Email: "maria.santos@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "system", LoginName: "system",
				FirstName: "OpsRamp", LastName: "System",
				Name: "OpsRamp System", Email: "system@opsramp.com",
			},
			CreatedDate: "2026-02-19T06:35:00+0000",
			UpdatedTime: "2026-02-19T09:00:00+0000",
			Source:      "ALERT",
			Category:    &opsramp.Category{ID: "1", UniqueID: "CAT-INF", Name: "Infrastructure"},
			SubCategory: &opsramp.Category{ID: "11", UniqueID: "SCAT-STOR", Name: "Storage"},
			SLADetails:  &opsramp.SLADetails{ResolutionBreach: true, ResponseBreach: true, ResponseTime: 1800, ResolutionTime: 14400},
			AlertIDs:    []string{"ALR-20260219-002"},
			ResourceIDs: []string{"res-005"},
		},
		{
			ID:          "INC-20260219-003",
			Subject:     "Payment service pod crash loop in GCP Kubernetes cluster",
			Description: "The payment-service pod on k8s-node-04 has been in CrashLoopBackOff for 2+ hours. Last exit code 137 indicates OOMKilled. The pod memory limit is set to 512Mi but the service appears to need more after the recent v2.3.1 deployment. Rolling back to v2.3.0 has been proposed.",
			Status:      "Open",
			SubStatus:   "Investigation",
			Priority:    "Urgent",
			AssignedTo: opsramp.User{
				ID: "usr-003", LoginName: "jpark",
				FirstName: "James", LastName: "Park",
				Name: "James Park", Email: "james.park@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "usr-001", LoginName: "achen",
				FirstName: "Alex", LastName: "Chen",
				Name: "Alex Chen", Email: "alex.chen@acme.com",
			},
			CreatedDate: "2026-02-19T10:00:00+0000",
			UpdatedTime: "2026-02-19T11:30:00+0000",
			Source:      "PORTAL",
			Category:    &opsramp.Category{ID: "2", UniqueID: "CAT-APP", Name: "Application"},
			SubCategory: &opsramp.Category{ID: "20", UniqueID: "SCAT-CONT", Name: "Container"},
			SLADetails:  &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 300, ResolutionTime: 3600},
			AlertIDs:    []string{"ALR-20260219-008"},
			ResourceIDs: []string{"res-016"},
		},
		{
			ID:          "INC-20260219-004",
			Subject:     "Staging server unreachable - monitoring-agent-staging-01",
			Description: "The staging monitoring agent at 172.16.0.50 has been unreachable for approximately 1 hour. All ping checks are failing. Physical hardware check has been requested from datacenter team.",
			Status:      "Open",
			SubStatus:   "Escalated",
			Priority:    "Normal",
			AssignedTo: opsramp.User{
				ID: "usr-004", LoginName: "psharma",
				FirstName: "Priya", LastName: "Sharma",
				Name: "Priya Sharma", Email: "priya.sharma@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "system", LoginName: "system",
				FirstName: "OpsRamp", LastName: "System",
				Name: "OpsRamp System", Email: "system@opsramp.com",
			},
			CreatedDate: "2026-02-19T11:05:00+0000",
			UpdatedTime: "2026-02-19T11:40:00+0000",
			Source:      "ALERT",
			Category:    &opsramp.Category{ID: "1", UniqueID: "CAT-INF", Name: "Infrastructure"},
			SubCategory: &opsramp.Category{ID: "12", UniqueID: "SCAT-AVAIL", Name: "Availability"},
			SLADetails:  &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 900, ResolutionTime: 10800},
			AlertIDs:    []string{"ALR-20260219-007"},
			ResourceIDs: []string{"res-025"},
		},
		{
			ID:          "INC-20260218-005",
			Subject:     "SSL certificate renewal for api.acme.com",
			Description: "SSL certificate for api.acme.com will expire on 2026-02-26. The certificate is managed via Let's Encrypt. Automatic renewal failed due to DNS challenge validation issue. Manual renewal process has been initiated.",
			Status:      "Open",
			SubStatus:   "In Progress",
			Priority:    "High",
			AssignedTo: opsramp.User{
				ID: "usr-005", LoginName: "dkim",
				FirstName: "David", LastName: "Kim",
				Name: "David Kim", Email: "david.kim@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "usr-001", LoginName: "achen",
				FirstName: "Alex", LastName: "Chen",
				Name: "Alex Chen", Email: "alex.chen@acme.com",
			},
			CreatedDate: "2026-02-18T10:00:00+0000",
			UpdatedTime: "2026-02-19T08:00:00+0000",
			Source:      "PORTAL",
			Category:    &opsramp.Category{ID: "3", UniqueID: "CAT-SEC", Name: "Security"},
			SubCategory: &opsramp.Category{ID: "30", UniqueID: "SCAT-CERT", Name: "Certificate"},
			SLADetails:  &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 1200, ResolutionTime: 86400},
			AlertIDs:    []string{"ALR-20260219-004"},
			ResourceIDs: []string{"res-010"},
		},
		// Resolved incidents (for historical context)
		{
			ID:          "INC-20260217-010",
			Subject:     "Network switch failure in datacenter-east rack 3",
			Description: "Top-of-rack switch in rack 3 failed, causing brief connectivity loss for 4 on-prem servers. Failover to redundant path completed in 45 seconds. Switch has been replaced.",
			Status:      "Resolved",
			SubStatus:   "Completed",
			Priority:    "Urgent",
			AssignedTo: opsramp.User{
				ID: "usr-004", LoginName: "psharma",
				FirstName: "Priya", LastName: "Sharma",
				Name: "Priya Sharma", Email: "priya.sharma@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "system", LoginName: "system",
				FirstName: "OpsRamp", LastName: "System",
				Name: "OpsRamp System", Email: "system@opsramp.com",
			},
			CreatedDate:  "2026-02-17T14:00:00+0000",
			UpdatedTime:  "2026-02-17T16:30:00+0000",
			ResolvedDate: "2026-02-17T16:30:00+0000",
			Source:       "ALERT",
			Category:     &opsramp.Category{ID: "1", UniqueID: "CAT-INF", Name: "Infrastructure"},
			SubCategory:  &opsramp.Category{ID: "13", UniqueID: "SCAT-NET", Name: "Network"},
			SLADetails:   &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 120, ResolutionTime: 9000},
			AlertIDs:     []string{},
			ResourceIDs:  []string{"res-025", "res-026", "res-027", "res-028"},
		},
		{
			ID:          "INC-20260215-011",
			Subject:     "Elasticsearch cluster yellow status - missing replicas",
			Description: "Elasticsearch cluster went yellow due to missing replica shards after node elasticsearch-prod-02 was removed for maintenance. Replicas re-allocated successfully after node was returned to service.",
			Status:      "Resolved",
			SubStatus:   "Completed",
			Priority:    "Normal",
			AssignedTo: opsramp.User{
				ID: "usr-001", LoginName: "achen",
				FirstName: "Alex", LastName: "Chen",
				Name: "Alex Chen", Email: "alex.chen@acme.com",
			},
			CreatedBy: opsramp.User{
				ID: "system", LoginName: "system",
				FirstName: "OpsRamp", LastName: "System",
				Name: "OpsRamp System", Email: "system@opsramp.com",
			},
			CreatedDate:  "2026-02-15T09:00:00+0000",
			UpdatedTime:  "2026-02-15T12:00:00+0000",
			ResolvedDate: "2026-02-15T12:00:00+0000",
			Source:       "ALERT",
			Category:     &opsramp.Category{ID: "1", UniqueID: "CAT-INF", Name: "Infrastructure"},
			SubCategory:  &opsramp.Category{ID: "14", UniqueID: "SCAT-SRCH", Name: "Search"},
			SLADetails:   &opsramp.SLADetails{ResolutionBreach: false, ResponseBreach: false, ResponseTime: 600, ResolutionTime: 10800},
			AlertIDs:     []string{},
			ResourceIDs:  []string{"res-009"},
		},
	}
}
